// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"

	"devops-go/basicdata/server/sys/internal/logic"
	"devops-go/basicdata/server/sys/internal/svc"
	"devops-go/basicdata/server/sys/sysclient"
)

type SysServer struct {
	svcCtx *svc.ServiceContext
	sysclient.UnimplementedSysServer
}

func NewSysServer(svcCtx *svc.ServiceContext) *SysServer {
	return &SysServer{
		svcCtx: svcCtx,
	}
}

func (s *SysServer) UserInfo(ctx context.Context, in *sysclient.InfoReq) (*sysclient.InfoResp, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

func (s *SysServer) UserAdd(ctx context.Context, in *sysclient.UserAddReq) (*sysclient.UserAddResp, error) {
	l := logic.NewUserAddLogic(ctx, s.svcCtx)
	return l.UserAdd(in)
}

func (s *SysServer) RedisAdd(ctx context.Context, in *sysclient.RedisReq) (*sysclient.RedisResp, error) {
	l := logic.NewRedisAddLogic(ctx, s.svcCtx)
	return l.RedisAdd(in)
}

func (s *SysServer) RedisDelete(ctx context.Context, in *sysclient.RedisReq) (*sysclient.RedisResp, error) {
	l := logic.NewRedisDeleteLogic(ctx, s.svcCtx)
	return l.RedisDelete(in)
}

func (s *SysServer) RedisUpdate(ctx context.Context, in *sysclient.RedisReq) (*sysclient.RedisResp, error) {
	l := logic.NewRedisUpdateLogic(ctx, s.svcCtx)
	return l.RedisUpdate(in)
}

func (s *SysServer) RedisGet(ctx context.Context, in *sysclient.RedisReq) (*sysclient.RedisResp, error) {
	l := logic.NewRedisGetLogic(ctx, s.svcCtx)
	return l.RedisGet(in)
}
