// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	sysuser "devops-go/api/internal/handler/sys/user"
	"devops-go/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户管理-新增用户
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: sysuser.UserAddHandler(serverCtx),
			},
			{
				// 用户管理-获取当前用户信息
				Method:  http.MethodGet,
				Path:    "/currentUser",
				Handler: sysuser.UserInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/sys/user"),
	)
}
