// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"devops-go/basicdata/api/internal/handler/redis"
	"net/http"

	sysuser "devops-go/basicdata/api/internal/handler/sys/user"
	"devops-go/basicdata/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户管理-新增用户
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: sysuser.UserAddHandler(serverCtx),
			},
			{
				// 用户管理-获取当前用户信息
				Method:  http.MethodGet,
				Path:    "/currentUser",
				Handler: sysuser.UserInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/sys/user"),
	)
	server.AddRoutes(
		[]rest.Route{
			{
				// Redis新增数据
				Method:  http.MethodPost,
				Path:    "/redisAdd",
				Handler: redis.RedisAddHandler(serverCtx),
			},
			{
				// Redis删除数据
				Method:  http.MethodPost,
				Path:    "/redisDelete",
				Handler: redis.RedisDeleteHandler(serverCtx),
			},
			{
				// Redis查询数据
				Method:  http.MethodGet,
				Path:    "/redisGet",
				Handler: redis.RedisGetHandler(serverCtx),
			},
			{
				// Redis修改数据
				Method:  http.MethodPost,
				Path:    "/redisUpdate",
				Handler: redis.RedisUpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/redis"),
	)
}
