basePath: /api
definitions:
  request.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  vo.LoginVo:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8082
info:
  contact: {}
  description: Devops-Go接口文档
  title: Devops-Go
  version: "1.0"
paths:
  /auth/checkToken:
    get:
      consumes:
      - application/json
      description: 检查 Token 是否有效
      produces:
      - application/json
      responses: {}
      summary: 检查 Token
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: 登录接口
      parameters:
      - description: 登录请求体
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.LoginVo'
      summary: 登录
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: 退出登录接口
      produces:
      - application/json
      responses: {}
      summary: 退出登录
      tags:
      - auth
swagger: "2.0"
